# [PRACTICA DE NUMPY](https://joserzapata.github.io/courses/python-ciencia-datos/numpy/)
## [Curso Python para Ciencia de datos](https://joserzapata.github.io/courses/python-ciencia-datos/)
### Por Jose R. Zapata - https://joserzapata.github.io/

<div class="alert alert-success">

<b>NOTA:</b> Realizar Primero los ejercicios y luego revisar las soluciones propuestas.

[Solucion Ejercicios Numpy - click para abrir](https://joserzapata.github.io/courses/python-ciencia-datos/numpy/2-practica_numpy-solucion/)

</div>

Los arreglos de numpy son la base de la computación científica en Python
- los dataframes de pandas para análisis de datos (Numpy era la unica base hasta pandas 1.5.3)
- los datos de entrada o salida para hacer Machine Learning con scikit-learn son arreglos de numpy

**Nota:** Es importante familiarizarse con el manejo de arreglos de numpy para poder hacer ciencia de datos con Python e identificar cuando usar un arreglo de numpy o un dataframe de pandas.

**Importe NumPy como np**

In [6]:
import numpy as np

**Cree un arreglo de ceros de 10 elementos**

In [ ]:
# Copie su código aqui

In [11]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**Cree un arreglo de unos de 10 elementos**

In [ ]:
# Copie su código aqui

In [12]:
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


**Cree un arreglo de cincos de 10 elementos**

In [ ]:
# Copie su código aqui

In [13]:
arr = np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


**Cree un arreglo de números enteros Del 10 al 50 (incluido)**

In [ ]:
# Copie su código aqui

In [14]:
arr = np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


**Cree un arreglo de los números enteros pares Del 10 al 50 (incluidos)**

In [ ]:
# Copie su código aqui

In [15]:
arr = np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


**Crear una matrix de 3x3 con valores del 0 al 8 (incluido)**

In [ ]:
# Copie su código aqui

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Crear la matriz identidad de 3x3**

In [ ]:
# Copie su código aqui

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Use NumPy para generar un numero aleatorio entre 0 y 1**

In [ ]:
# Copie su código aqui

array([0.2369713])

**Use NumPy para generar un arreglo de 25 números aleatorios que sean de la distribucion normal estandar**

In [ ]:
# Copie su código aqui

array([-1.82518925,  0.35985968,  0.7908014 ,  1.09115394, -1.18145353,
       -0.38358405, -0.1049287 ,  1.27313964,  0.05365275, -0.63835531,
        0.4984666 , -1.60464831, -0.84688945,  0.4695778 ,  1.73142269,
       -1.63808225, -0.67171648, -0.14015625,  0.50828476,  0.60145966,
       -0.34493194,  0.09632452, -0.85907492, -0.46924336,  1.22406872])

**Cree un arreglo de 20 elementos linealmente espaciados entre 0 y 1:**

In [ ]:
# Copie su código aqui

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

**Indexacion y seleccion con Numpy**

Crear una matriz con numeros del 1 al 25 y que tenga forma de 5x5



In [ ]:
# Copie su código aqui


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

replique los resultados que siguen:


In [ ]:
# Copie su código aqui

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# Copie su código aqui

20

In [ ]:
# Copie su código aqui

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# Copie su código aqui

array([21, 22, 23, 24, 25])

In [ ]:
# Copie su código aqui

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Obtenga la suma de todos los valores de la matriz**

In [ ]:
# Copie su código aqui

325

**Obtenga la desviación estándar de los valores de la matriz**

In [ ]:
# Copie su código aqui

7.211102550927978

**Obtener la suma de cada una de las columnas de la matriz**

In [ ]:
# Copie su código aqui

array([55, 60, 65, 70, 75])

## Referencia

https://joserzapata.github.io/courses/python-ciencia-datos/numpy/