<a href="https://colab.research.google.com/github/greg0910/Learning_Numpy_py/blob/main/notebooks/Ejercicios_curso_python_ciencia_datos/2-Practica_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [PRACTICA DE NUMPY](https://joserzapata.github.io/courses/python-ciencia-datos/numpy/)
## [Curso Python para Ciencia de datos](https://joserzapata.github.io/courses/python-ciencia-datos/)
### Por Jose R. Zapata - https://joserzapata.github.io/

<div class="alert alert-success">

<b>NOTA:</b> Realizar Primero los ejercicios y luego revisar las soluciones propuestas.

[Solucion Ejercicios Numpy - click para abrir](https://joserzapata.github.io/courses/python-ciencia-datos/numpy/2-practica_numpy-solucion/)

</div>

Los arreglos de numpy son la base de la computación científica en Python
- los dataframes de pandas para análisis de datos (Numpy era la unica base hasta pandas 1.5.3)
- los datos de entrada o salida para hacer Machine Learning con scikit-learn son arreglos de numpy

**Nota:** Es importante familiarizarse con el manejo de arreglos de numpy para poder hacer ciencia de datos con Python e identificar cuando usar un arreglo de numpy o un dataframe de pandas.

**Importe NumPy como np**

In [2]:
import numpy as np

**Cree un arreglo de ceros de 10 elementos**

In [ ]:
# Copie su código aqui

In [8]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**Cree un arreglo de unos de 10 elementos**

In [ ]:
# Copie su código aqui

In [9]:
arr= np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


**Cree un arreglo de cincos de 10 elementos**

In [ ]:
# Copie su código aqui

In [10]:
arr= np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


**Cree un arreglo de números enteros Del 10 al 50 (incluido)**

In [ ]:
# Copie su código aqui

In [11]:
arr = np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


**Cree un arreglo de los números enteros pares Del 10 al 50 (incluidos)**

In [ ]:
# Copie su código aqui

In [12]:
arr=np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


**Crear una matrix de 3x3 con valores del 0 al 8 (incluido)**

In [ ]:
# Copie su código aqui

In [13]:
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Crear la matriz identidad de 3x3**

In [ ]:
# Copie su código aqui

In [17]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Use NumPy para generar un numero aleatorio entre 0 y 1**

In [ ]:
# Copie su código aqui

In [15]:
arr=np.random.rand()
print(arr)

0.8843895247838128


**Use NumPy para generar un arreglo de 25 números aleatorios que sean de la distribucion normal estandar**

In [ ]:
# Copie su código aqui

In [19]:
arr=np.random.randn(5,5)
print(arr)

[[-1.37531687 -0.85044919  0.56496625 -1.092533    1.60089998]
 [ 0.9303463  -0.18553748  0.92265637  1.58501556 -0.27098258]
 [ 1.45534871 -1.39822501 -0.30254543  1.88893373 -1.37261496]
 [-0.05946252  0.82020775 -1.33721735 -0.33014643 -0.45656924]
 [-0.05846545 -1.90594113 -0.60330673 -0.03068248 -0.19562987]]


**Cree un arreglo de 20 elementos linealmente espaciados entre 0 y 1:**

In [ ]:
# Copie su código aqui

In [20]:
arr=np.linspace(0,1,20)
print(arr)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


**Indexacion y seleccion con Numpy**

Crear una matriz con numeros del 1 al 25 y que tenga forma de 5x5



In [ ]:
# Copie su código aqui


In [62]:
arr=np.arange(1,26).reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


replique los resultados que siguen:


In [ ]:
# Copie su código aqui

In [50]:
sub_matriz = arr[2:5, 1:5]  # Filas 2 a 4 (incluidas) y columnas 1 a 4 (incluidas)
print(sub_matriz)


[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
# Copie su código aqui

In [51]:
arr_20=sub_matriz[1,3]
print(arr_20)

20


In [ ]:
# Copie su código aqui

In [53]:
arr_3=sub_matriz[:3,:1]
print(arr_3)

[[12]
 [17]
 [22]]


In [ ]:
# Copie su código aqui

In [57]:
ultima_fila = sub_matriz[2, :]
print(ultima_fila)

[22 23 24 25]


In [ ]:
# Copie su código aqui

In [63]:
dos_ultimas=arr[3:5,:5]
print(dos_ultimas)

[[16 17 18 19 20]
 [21 22 23 24 25]]


**Obtenga la suma de todos los valores de la matriz**

In [ ]:
# Copie su código aqui

In [64]:
sum_total=np.sum(arr)
print(sum_total)

325


**Obtenga la desviación estándar de los valores de la matriz**

In [ ]:
# Copie su código aqui

In [65]:
desv=np.std(arr)
print(desv)

7.211102550927978


**Obtener la suma de cada una de las columnas de la matriz**

In [ ]:
# Copie su código aqui

In [66]:
suma_columnas=np.sum(arr,axis=0)
print(suma_columnas)

[55 60 65 70 75]


## Referencia

https://joserzapata.github.io/courses/python-ciencia-datos/numpy/